### ISSUE TITLE
Error: ENOTDIR: not a directory with node-fetch

### ISSUE THREAD

**Issue by manesid** [queelag/core#2]
I am encountering an error related to node-fetch when running my Electron application. The error message indicates a directory issue, specifically ENOTDIR: not a directory.

### Steps to Reproduce:

1. Install the @aracna/core:1.1.89 package in an Electron application.
2. Package the application using electron-builder.
3. Attempt to run the application.
4. The error is triggered.

### Environment:

node-fetch Version: 3.3.2
Node.js Version: 20.9.0
Electron Version: 24.5.1
Operating System: Windows 10, macOS 14
Package Manager: 10.1.0

### Attempted Solutions:

1. Cleared npm cache and reinstalled dependencies.
2. Unpacked the asar archive to verify the node-fetch module exists and is structured correctly.
3. Downgraded/Upgraded node-fetch to different versions to test compatibility.

**Comment by najeebkhan14** [comment]
@manesid I'm facing same issue. How did you resolve it?
